I/O redirection, better autostart, etc.

diff --git a/.scripts/default-apps/launch b/.scripts/default-apps/launch
--- a/.scripts/default-apps/launch
+++ b/.scripts/default-apps/launch
@@ -9,11 +9,11 @@ MAGENTA='\033[1;35m'
 NC='\033[0m' # No Color
 
 function checkdep {
-    which $1 >/dev/null 2>&1 || err "$1 is not installed. Please install it first!"
+    which $1 2> /dev/null || err "$1 is not installed. Please install it first!"
 }
 
 function err {
-    echo -e "${RED}$@${NC}"
+    echo -e "$(tput bold)$(tput setaf 1)==> Error:$(tput sgr0) $@"
     exit 1
 }
 
@@ -52,7 +52,7 @@ case $1 in
         checkdep $TEXT_EDITOR
         $TEXT_EDITOR $DEFAPPS_FILE || exit 1
     ;;
-    "")
+    ""|-h|--help)
         apps
     ;;
     *)
@@ -62,7 +62,7 @@ case $1 in
             [[ ! -z $2 ]] && bash -c "$filt $opt &> /dev/null &" && exit 0
             [[ ! -z $1 ]] && bash -c "$filt &> /dev/null &"
         else
-            which $1 >/dev/null 2>&1 || err "$1 is not in database. Please define it first \"--edit\"!"
+            which $1 2> /dev/null || err "$1 is not in database. Please define it first \"--edit\"!"
         fi
     ;;
 esac
