Bash Scripts: Fixed deps checking, if conditions, etc.

diff --git a/.ncmpcpp/scripts/single-album b/.ncmpcpp/scripts/single-album
--- a/.ncmpcpp/scripts/single-album
+++ b/.ncmpcpp/scripts/single-album
@@ -1,36 +1,36 @@
 #!/usr/bin/env bash
 source $HOME/.owl4ce_var
 
-command -v {"mpd","mpc"} > /dev/null 2>&1 || exit 1
+type -p {"mpd","mpc"} &> /dev/null || exit 1
 
 w3m() {
-    [[ "$1" = "clear" ]] && printf "\ec" && exit 0    
+    [[ "$1" = "clear" ]] && printf "\ec" && exit 0 || :
     shopt -s nullglob
     w3m_paths=({/usr/{local/,},~/.nix-profile/}{lib,libexec,lib64,libexec64}/w3m/w3mi*)
     shopt -u nullglob
     
-    [[ -x "${w3m_paths[0]}" ]] && w3m_img_path="${w3m_paths[0]}"
-    if command -v {"xprop","xwininfo"} &> /dev/null; then
-        win_id="$(xprop -root _NET_ACTIVE_WINDOW | awk -F'# ' '{print $2}' 2> /dev/null)"
+    [[ -x "${w3m_paths[0]}" ]] && w3m_img_path="${w3m_paths[0]}" || :
+    if type -p {"xprop","xwininfo"} &> /dev/null; then
+        win_id="$(xprop -root _NET_ACTIVE_WINDOW | awk -F'# ' '{print $2}')"
         while true; do
-            #get_height="$(xwininfo -id $win_id | awk -F ':' '/Height/{print $2}' 2> /dev/null)"
-            get_width="$(xwininfo -id $win_id | awk -F ':' '/Width/{print $2}' 2> /dev/null)"
-            #h_size="$(bc <<< $get_height/1.29 2> /dev/null)"
-            w_size="$(bc <<< $get_width/1.166 2> /dev/null)"
+            #get_height="$(xwininfo -id $win_id | awk -F ':' '/Height/{print $2}')"
+            get_width="$(xwininfo -id $win_id | awk -F ':' '/Width/{print $2}')"
+            #h_size="$(bc <<< $get_height/1.29)"
+            w_size="$(bc <<< $get_width/1.166)"
             
-            read -rt "1" <> <(:) || :
+            read -rt ".5" <> <(:) || :
             
             # Keep aspect ratio by depend on width for both
             printf '%b\n%s;\n%s\n' "0;1;0;0;$w_size;$w_size;;;;;${COVER}" 3 4 | "${w3m_img_path:-false}" &> /dev/null
         done
     else
-        read -rt "1" <> <(:) || :
-        printf >&2 "\ecerror > xorg-xprop and/or xorg-xwininfo not installed!"
+        read -rt ".5" <> <(:) || :
+        printf >&2 "\ec\e[1;31merror:\e[0m xorg-xprop and xorg-xwininfo not installed!"
     fi
 }
 
 pixbuf() {
-    [[ "$1" = "clear" ]] && printf "\e]20;;100x100+1000+1000\a" && exit 0
+    [[ "$1" = "clear" ]] && printf "\e]20;;100x100+1000+1000\a" && exit 0 || :
     printf "\e]20;${COVER};86x86+04+04:op=keep-aspect\a"
 }
 
@@ -41,7 +41,7 @@ COVER="$NCMPCPP_COVER"
     album="$(mpc --format %album% current -p 6600)"
     file="$(mpc --format %file% current -p 6600)"
     album_dir="${file%/*}"
-    [[ -z "$album_dir" ]] && exit 1
+    [[ -z "$album_dir" ]] && exit 1 || :
     album_dir="$MUSIC_DIR/$album_dir"
 
     covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
