Bash Scripts: Deps checking, stderr, minmod tray

diff --git a/.ncmpcpp/scripts/single-album b/.ncmpcpp/scripts/single-album
--- a/.ncmpcpp/scripts/single-album
+++ b/.ncmpcpp/scripts/single-album
@@ -10,7 +10,7 @@ w3m() {
     shopt -u nullglob
     
     [[ -x "${w3m_paths[0]}" ]] && w3m_img_path="${w3m_paths[0]}" || :
-    if type -p {"xprop","xwininfo"} &> /dev/null; then
+    if type -p {"xprop","xwininfo","bc"} &> /dev/null; then
         win_id="$(xprop -root _NET_ACTIVE_WINDOW | awk -F'# ' '{print $2}')"
         while true; do
             #get_height="$(xwininfo -id $win_id | awk -F ':' '/Height/{print $2}')"
@@ -25,7 +25,7 @@ w3m() {
         done
     else
         read -rt ".5" <> <(:) || :
-        printf >&2 "\ec\e[1;31merror:\e[0m xorg-xprop and xorg-xwininfo not installed!"
+        printf "\ec\e[1;31merror: \e[0;32mxorg-xprop\e[0m, \e[0;32mxorg-xwininfo\e[0m, and \e[0;32mbc\e[0m not installed!" >&2
     fi
 }
 
