Bash scripts: Simplify, use built-in, etc.

diff --git a/.config/tint2/executor/temp b/.config/tint2/executor/temp
--- a/.config/tint2/executor/temp
+++ b/.config/tint2/executor/temp
@@ -4,12 +4,5 @@ source $HOME/.owl4ce_var
 temp_dev_path="/sys/devices/virtual/thermal"
 
 [[ -d "$temp_dev_path/$TEMP_DEV" ]] && \
-
-get_temp() {
-    CEL=$'\xc2\xb0C'
-    temp="$(cat $temp_dev_path/$TEMP_DEV/temp 2> /dev/null)"
-    temp="$(expr $temp / 1000)"
-    echo "$temp$CEL"
-}
-
-get_temp || echo "$TEMP_DEV not found!"; exit 1
+echo "$(expr $(cat $temp_dev_path/$TEMP_DEV/temp) / 1000)"$'\xc2\xb0C' \
+|| echo "$TEMP_DEV not found!"; exit 1
