Bash scripts: Checking dependencies, if conditions, etc.

diff --git a/.config/tint2/executor/temp b/.config/tint2/executor/temp
--- a/.config/tint2/executor/temp
+++ b/.config/tint2/executor/temp
@@ -1,11 +1,15 @@
 #!/usr/bin/env bash
 source $HOME/.owl4ce_var
 
+temp_dev_path="/sys/devices/virtual/thermal"
+
+[[ -d $temp_dev_path/$TEMP_DEV ]] && \
+
 get_temp() {
     CEL=$'\xc2\xb0C'
-    temp="$(cat /sys/devices/virtual/thermal/$TEMP_DEV/temp)"
+    temp="$(cat $temp_dev_path/$TEMP_DEV/temp)"
     temp="$(expr $temp / 1000)"
     echo "$temp$CEL"
 }
 
-get_temp
+get_temp || echo "$TEMP_DEV not found!"; exit 1
